INSERT INTO EAI.ROUTING (KEY_INTEGRATION, KEY_ROUTING, HOLD, MESSAGE_MAPPING_SPECIFIER, 
MAPPING_QUEUE_MANAGER, MAPPING_QUEUE, QUEUE_MANAGER, QUEUE, CREATE_DATE, START_DATE, END_DATE) 
VALUES (10231, 10572, 0, 'ELSIP_TO_DW', 'MQBDEV2', 'FROM.FUELDELIVERY.RECEIPT', 'MQBDEV2','FUEL.TO.DW.ESLIP', 
CURRENT_DATE, CURRENT_DATE, '31.12.9999')