INSERT INTO EAI.ROUTING (KEY_INTEGRATION, KEY_ROUTING, HOLD, MESSAGE_MAPPING_SPECIFIER, 
MAPPING_QUEUE_MANAGER, MAPPING_QUEUE, QUEUE_MANAGER, QUEUE, CREATE_DATE, START_DATE, END_DATE) 
VALUES (10164, 10418, 0, 'ELSIP_TO_DW', 'MQBPRD2', 'FROM.FUELDELIVERY.RECEIPT', 'MQBPRD2','FUEL.TO.DW.ESLIP', 
CURRENT_DATE, CURRENT_DATE, '31.12.9999')