-- Retrieve KEY_INTEGRATION values for the inserted rows
SELECT SENDER_CODE,RECEIVER_CODE, MESSAGE_TYPE,KEY_INTEGRATION FROM EAI.INTEGRATION 
WHERE 
MESSAGE_TYPE = 'FROM.FUELDELIVERY.RECEIPT' AND RECEIVER_CODE IN ('DW') ORDER BY KEY_INTEGRATION WITH UR;


---> 10418