-- MQBPRD2 (v9 )

INSERT INTO EAI.INTEGRATION (SENDER_QUALIFIER, SENDER_CODE, RECEIVER_QUALIFIER, RECEIVER_CODE, MESSAGE_TYPE, 
MESSAGE_VERSION, COMPANY_CODE, LOG_LEVEL, CREATE_DATE, START_DATE, END_DATE) 
VALUES ('E1', 'EAI', 'Rx', 'DW', 'FROM.FUELDELIVERY.RECEIPT', 'n/a', '999999', 1, 
CURRENT_DATE, CURRENT_DATE, '31.12.9999')

--> 